name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build application
        run: echo "Building Application..."

      - name: Print runtime version
        run: |
          echo "Node version:"
          node --version
          echo "npm version:"
          npm --version

      - name: Test application
        run: echo "Running tests..."
